import streamlit as st
import pandas as pd
import sqlite3
import os
from langchain_community.utilities import SQLDatabase
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_classic.chains import create_sql_query_chain
# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="IPL Intelligence Platform", page_icon="🏏", layout="wide")

# --- SECURE API KEY HANDLING ---
# Streamlit Cloud uses "Secrets" to hide your API key from the public.
if "GOOGLE_API_KEY" not in os.environ:
    # This grabs the key from Streamlit's secure vault when hosted online
    os.environ["GOOGLE_API_KEY"] = st.secrets.get("GOOGLE_API_KEY", "AQ.Ab8RN6LXZe8iPyHaMLhorWIOqjbZk4z2aB9h6OltDoqBTWVy9Q")

# --- DATABASE CONNECTION ---
db_path = "ipl_history.db"
# We use st.cache_resource so it doesn't reconnect on every button click
@st.cache_resource
def get_db_connection():
    return sqlite3.connect(db_path, check_same_thread=False)

conn = get_db_connection()

# ==========================================
# UI SECTION 1: VISUAL AGGREGATION PLATFORM
# ==========================================
st.title("🏏 IPL Intelligent Data Platform")
st.markdown("Explore the historical IPL database, or ask the AI a question to generate complex insights.")

st.subheader("📊 Data Explorer")

# Load the matches table
df_matches = pd.read_sql("SELECT * FROM matches", conn)

# FIX: Convert the 'season' column to a string to prevent PyArrow crashes
df_matches['season'] = df_matches['season'].astype(str)

# FIX: Updated parameter from 'use_container_width=True' to 'width="stretch"'
st.dataframe(df_matches, width="stretch", height=300)

st.divider()

# ==========================================
# UI SECTION 2: AI SQL ASSISTANT (HUMAN IN THE LOOP)
# ==========================================
st.subheader("🤖 AI Database Agent")

# Initialize a session state variable to store the SQL generated by the LLM
if "generated_sql" not in st.session_state:
    st.session_state.generated_sql = ""

# The search bar
user_question = st.text_input("Ask a complex question (e.g., 'Which team has the highest win margin by runs?'):")

if st.button("Generate Query"):
    if user_question:
        with st.spinner("Analyzing schema and writing SQL..."):
            # 1. Setup Langchain (We only need the write_query chain here, not the execution chain)
            db = SQLDatabase.from_uri(f"sqlite:///{db_path}", sample_rows_in_table_info=3)
            llm = ChatGoogleGenerativeAI(model="gemini-3.5-flash", temperature=0)
            write_query_chain = create_sql_query_chain(llm, db)
            
            # 2. Generate the raw SQL
            raw_query = write_query_chain.invoke({"question": user_question})
            
            # 3. Clean the formatting
            clean_query = raw_query.replace("```sql", "").replace("```", "").strip()
            if "SQLQuery:" in clean_query:
                clean_query = clean_query.split("SQLQuery:", 1)[1].strip()
                
            # 4. Store it in session state so the user can review it
            st.session_state.generated_sql = clean_query

# ==========================================
# UI SECTION 3: REVIEW & EXECUTE
# ==========================================
# If a query exists in the session state, display the editor
if st.session_state.generated_sql:
    st.info("💡 **Review the generated SQL below.** You can edit it manually before running it against the database.")
    
    # st.text_area allows the user to manually edit the LLM's output
    edited_sql = st.text_area("SQL Query", value=st.session_state.generated_sql, height=150)
    
    if st.button("▶️ Execute Query"):
        with st.spinner("Running query..."):
            try:
                # Execute the edited SQL directly via Pandas to get a beautiful table output
                result_df = pd.read_sql(edited_sql, conn)
                st.success("Query executed successfully!")
                st.dataframe(result_df, use_container_width=True)
            except Exception as e:
                st.error(f"Database Error: {e}")
